language: erlang
sudo: false

os: linux
otp_release: 19.3

matrix:
  include:
    - os: linux
      otp_release: 18.3
    - os: linux
      otp_release: 19.3
    - os: linux
      otp_release: 20.0

script: "make compile test REBAR=./rebar3"

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

notifications:
  recipients:
    - jesper.louis.andersen@gmail.com
